export const cities = [
  "Albuquerque, NM",
  "Arlington, VA",
  "Atlanta, GA",
  "Austin, TX",
  "Baltimore, MD",
  "Boston, MA",
  "Charlotte, NC",
  "Chicago, IL",
  "Cleveland, OH",
  "Colorado Springs, CO",
  "Columbus, OH",
  "Dallas, TX",
  "Denver, CO",
  "Detroit, MI",
  "El Paso, TX",
  "Fort Worth, TX",
  "Fresno, CA",
  "Houston, TX",
  "Indianapolis, IN",
  "Jacksonville, FL",
  "Kansas City, MO",
  "Las Vegas, NV",
  "Los Angeles, CA",
  "Louisville, KY",
  "Memphis, TN",
  "Mesa, AZ",
  "Miami, FL",
  "Milwaukee, WI",
  "Minneapolis, MN",
  "Nashville, TN",
  "New Orleans, LA",
  "New York City, NY",
  "Oakland, CA",
  "Oklahoma City, OK",
  "Omaha, NE",
  "Philadelphia, PA",
  "Poenix, AZ",
  "Portland, OR",
  "Raleigh, NC",
  "Sacramento, CA",
  "San Antonio, TX",
  "San Diego, CA",
  "San Francisco, CA",
  "San Jose, CA",
  "Seattle, WA",
  "Tucson, AZ",
  "Tulsa, OK",
  "Virginia Beach, VA",
  "Washington, DC",
  "Wichita, KS"
];

const categoryNames = [
  "Accounting / Finance/",
  "Administration/",
  "Business / Operations / Strategy/",
  "Creative / Design",
  "Customer Service / Retail",
  "Data / Analytics",
  "Editorial",
  "Education",
  "Engineering",
  "Fundraising / Development",
  "Health / Wellness / Fitness",
  "Healthcare / Medicine",
  "Human Resources / Recruiting",
  "Information Technology / Software",
  "Insurance / Claims",
  "Legal",
  "Management",
  "Marketing / PR / Media",
  "Sales"
];

export const categories = [
  "creative design",
  "sales",
  "legal",
  "education",
  "editorial",
  "business operations strategy",
  "human resources recruiting",
  "management",
  "health wellness fitness",
  "data analytics",
  "healthcare medicine",
  "administration",
  "marketing pr media",
  "information technology software",
  "engineering",
  "accounting finance",
  "insurance claims",
  "customer service retail",
  "fundraising development"
];
