export const cities = [
  "Albuquerque, NM",
  "Arlington, VA",
  "Atlanta, GA",
  "Austin, TX",
  "Baltimore, MD",
  "Boston, MA",
  "Charlotte, NC",
  "Chicago, IL",
  "Cleveland, OH",
  "Colorado Springs, CO",
  "Columbus, OH",
  "Dallas, TX",
  "Denver, CO",
  "Detroit, MI",
  "El Paso, TX",
  "Fort Worth, TX",
  "Fresno, CA",
  "Houston, TX",
  "Indianapolis, IN",
  "Jacksonville, FL",
  "Kansas City, MO",
  "Las Vegas, NV",
  "Los Angeles, CA",
  "Louisville, KY",
  "Memphis, TN",
  "Mesa, AZ",
  "Miami, FL",
  "Milwaukee, WI",
  "Minneapolis, MN",
  "Nashville, TN",
  "New Orleans, LA",
  "New York City, NY",
  "Oakland, CA",
  "Oklahoma City, OK",
  "Omaha, NE",
  "Philadelphia, PA",
  "Poenix, AZ",
  "Portland, OR",
  "Raleigh, NC",
  "Sacramento, CA",
  "San Antonio, TX",
  "San Diego, CA",
  "San Francisco, CA",
  "San Jose, CA",
  "Seattle, WA",
  "Tucson, AZ",
  "Tulsa, OK",
  "Virginia Beach, VA",
  "Washington, DC",
  "Wichita, KS"
];

export const categoryNames = [
  "Accounting / Finance",
  "Administration",
  "Business / Operations / Strategy",
  "Creative / Design",
  "Customer Service / Retail",
  "Data / Analytics",
  "Editorial",
  "Education",
  "Engineering",
  "Fundraising / Development",
  "Health / Wellness / Fitness",
  "Healthcare / Medicine",
  "Human Resources / Recruiting",
  "Information Technology / Software",
  "Insurance / Claims",
  "Legal",
  "Management",
  "Marketing / PR / Media",
  "Sales"
];

export const categories = [
  "accounting finance",
  "administration",
  "business operations strategy",
  "creative design",
  "customer service retail",
  "data analytics",
  "editorial",
  "education",
  "engineering",
  "fundraising development",
  "health wellness fitness",
  "healthcare medicine",
  "human resources recruiting",
  "information technology software",
  "insurance claims",
  "legal",
  "management",
  "marketing pr media",
  "sales"
];
